export { default as Hero } from "./Hero/Hero";
export { default as Services } from "./Services/Services";
export { default as Gallery } from "./Gallery/Gallery";
export { default as About } from "./About/About";
export { default as Doctors } from "./Doctors/Doctors";
export { default as Map } from "./Map/Map";
export { default as Footer } from "./Footer/Footer";
export { default as News } from "./News/News";
export { default as Owner } from "./Owner/Owner";
